$ANSIBLE_VAULT;1.1;AES256
66326533643634323964616137623035303464393638396162306634376135663432393862663035
6531363836373332313966396166663864373562346432320a666365373735343133363161663931
66323463393565663839363064303361353464656364663837636533343330353233356433666438
6430636437333833300a333366613863633865303136656265666631366164623836333461343532
64393938616663303530313763663932666533333965383338356333616564366465633439663266
33313637343961313038303033663533656462326163646430653065613163376266636333343262
32343164396666653236353331333265353637346266303138353461653238643166663137366237
38656361613236643535626264336461663732616363623732623733346561313836366431323332
63326131306332383866613739303732363665386263363266363061393230646431636438663966
35316434363537336635363535636436313965363865646433623435306663366233643866613265
306561626566623532396139653138306537
